# Generated by Django 4.2 on 2024-03-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0002_atnfpulsar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atnfpulsar',
            name='DM',
            field=models.FloatField(blank=True, null=True, verbose_name='Dispersion Measure (cm^-3 pc)'),
        ),
        migrations.AlterField(
            model_name='atnfpulsar',
            name='p0',
            field=models.FloatField(blank=True, null=True, verbose_name='Barycentric period of the pulsar (s)'),
        ),
        migrations.AlterField(
            model_name='atnfpulsar',
            name='s400',
            field=models.FloatField(blank=True, null=True, verbose_name='Mean flux density at 400 MHz (mJy)'),
        ),
    ]
