# Generated by Django 4.2 on 2024-03-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0003_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='candidate_app.project'),
            preserve_default=False,
        ),
    ]
