# Generated by Django 4.2 on 2024-07-26 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0003_alter_atnfpulsar_dm_alter_atnfpulsar_p0_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='candidate_app.candidate')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Metadata relevant to this candidate')),
            ],
        ),
    ]
