# Generated by Django 4.2 on 2024-07-29 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0004_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='associated', serialize=False, to='candidate_app.candidate')),
                ('pulsar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated', to='candidate_app.atnfpulsar')),
            ],
        ),
    ]
