# Generated by Django 4.2 on 2024-03-07 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate_app', '0004_candidate_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Classification')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='filter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='candidate_app.filter'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='obs_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='candidate_app.observation', verbose_name='Observation ID in GPS time'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='candidate_app.project'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='candidate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='candidate_app.candidate'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='classification',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='candidate_app.classification'),
        ),
    ]
